In [1]:
import numpy as np

## Datatypes and attributes

In [2]:
# Numpy main dataype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
                [4,5,6.5],
                [7,8,9]])
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5],
       [7. , 8. , 9. ]])

In [9]:
a3 = np.array([[[1,2,3],[23,17,12]],[[10,11,21],[12,34,34]]])
a3

array([[[ 1,  2,  3],
        [23, 17, 12]],

       [[10, 11, 21],
        [12, 34, 34]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(3, 3)

In [13]:
a3.shape

(2, 2, 3)

In [14]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [16]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.size , a2.size , a3.size

(3, 9, 12)

In [18]:
 # create a dataframe from numpy array
import pandas as pd 


df = pd.DataFrame(a2)
df


0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5
2  7.0  8.0  9.0

## Creating Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [26]:
ones = np.ones((3,2), dtype=int)
ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [28]:
zeros = np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
range_array = np.arange(1,99,3)
range_array

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [41]:
random_array = np.random.randint(low=0 , high=10,size=(5,6))
random_array

array([[7, 3, 4, 9, 0, 0],
       [7, 4, 1, 1, 2, 1],
       [8, 2, 9, 6, 7, 6],
       [1, 4, 5, 2, 0, 8],
       [3, 1, 2, 8, 7, 2]])

In [42]:
random_array.shape

(5, 6)

In [43]:
np.random.random((5,6))

array([[0.46178343, 0.54537578, 0.5919319 , 0.98392325, 0.64401413,
        0.2642878 ],
       [0.33848483, 0.22262535, 0.87755241, 0.59705441, 0.67550693,
        0.88711293],
       [0.40359159, 0.69024061, 0.76583709, 0.83366245, 0.69474633,
        0.19336317],
       [0.90796751, 0.17492284, 0.24028924, 0.35483739, 0.42056786,
        0.36588858],
       [0.71090371, 0.71511483, 0.68250551, 0.31833434, 0.16296312,
        0.31899807]])

In [45]:
random_array3 = np.random.rand(6,7)
random_array3

array([[0.19158156, 0.46258978, 0.49182903, 0.63265193, 0.76148781,
        0.30644638, 0.14531131],
       [0.24710071, 0.67389341, 0.69452811, 0.36190883, 0.22255433,
        0.00870548, 0.62612831],
       [0.7354682 , 0.89731989, 0.3562467 , 0.48583633, 0.60776664,
        0.39440506, 0.34971832],
       [0.44829539, 0.67196042, 0.42629639, 0.53700828, 0.04477481,
        0.27106511, 0.88391082],
       [0.25150804, 0.17704859, 0.9199583 , 0.27870103, 0.97321237,
        0.5495689 , 0.41691659],
       [0.16024586, 0.17656912, 0.35167573, 0.98056799, 0.98609503,
        0.69877938, 0.21276195]])

In [58]:
#pseudo random numbers

np.random.seed(0)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

### Viewing arrays and matrices

In [59]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
  a1


array([1, 2, 3])

In [61]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5],
       [7. , 8. , 9. ]])

In [62]:
a3

array([[[ 1,  2,  3],
        [23, 17, 12]],

       [[10, 11, 21],
        [12, 34, 34]]])

In [63]:
a1[0]

1

In [64]:
a2[0]

array([1., 2., 3.])

In [65]:
a3[0]

array([[ 1,  2,  3],
       [23, 17, 12]])

In [66]:
a2[1]

array([4. , 5. , 6.5])

In [68]:
a3[:2,:2,:3]

array([[[ 1,  2,  3],
        [23, 17, 12]],

       [[10, 11, 21],
        [12, 34, 34]]])

In [69]:
random_array5 = np.random.randint(10,size=(2,3,4,5))
random_array5

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [70]:
random_array5.shape

(2, 3, 4, 5)

In [71]:
random_array5.ndim

4

In [76]:
## get the only first 4 numbers
random_array5[:1,:1,:2,:3]

array([[[[6, 7, 7],
         [5, 9, 8]]]])

## Manipulating and comparing ararys

### Arithmetic

In [77]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [78]:
a1

array([1, 2, 3])

In [79]:
a1+ones

array([2., 3., 4.])

In [80]:
a1-ones

array([0., 1., 2.])

In [81]:
a1*ones

array([1., 2., 3.])

In [82]:
a1*2*ones

array([2., 4., 6.])